### ISSUE TITLE
[BUG FE] Cannot register when providing a email address

### ISSUE THREAD

**Issue by BobWritesCode** [BobWritesCode/squadup_frontend#43]
**Describe the bug** (A clear and concise description of what the bug is)
When trying to register a new account with email address, nothing seems to happen but can see an error in the console.

**To Reproduce** (Steps to reproduce the behavior)
Try to create a new account with an eamil address.

**Expected behaviour** (A clear and concise description of what you expected to happen)
Account is created and user is taken to the sign in page.

**Screenshots** (If applicable, add screenshots to help explain your problem)
![image](https://github.com/BobWritesCode/squadup_frontend/assets/104802720/db06ef82-5811-4516-b99a-7eedc65820eb)
![image](https://github.com/BobWritesCode/squadup_frontend/assets/104802720/3c275d2a-bea9-43f8-aedc-9d2fe74f26f4)

**Additional context** (Add any other context about the problem here)
`Internal Server Error: /dj-rest-auth/registration/
Traceback (most recent call last):
  File "C:\Users\Warwick\Documents\Git\SquadUp\SquadUp_api\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Warwick\Documents\Git\SquadUp\SquadUp_api\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Warwick\Documents\Git\SquadUp\SquadUp_api\venv\Lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Warwick\Documents\Git\SquadUp\SquadUp_api\venv\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Warwick\Documents\Git\SquadUp\SquadUp_api\venv\Lib\site-packages\django\utils\decorators.py", line 46, in _wrapper
    return bound_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Warwick\Documents\Git\SquadUp\SquadUp_api\venv\Lib\site-packages\django\views\decorators\debug.py", line 92, in sensitive_post_parameters_wrapper
    return view(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Warwick\Documents\Git\SquadUp\SquadUp_api\venv\Lib\site-packages\dj_rest_auth\registration\views.py", line 42, in dispatch
    return super().dispatch(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Warwick\Documents\Git\SquadUp\SquadUp_api\venv\Lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Warwick\Documents\Git\SquadUp\SquadUp_api\venv\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\Warwick\Documents\Git\SquadUp\SquadUp_api\venv\Lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\Warwick\Documents\Git\SquadUp\SquadUp_api\venv\Lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Warwick\Documents\Git\SquadUp\SquadUp_api\venv\Lib\site-packages\rest_framework\generics.py", line 190, in post
    return self.create(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Warwick\Documents\Git\SquadUp\SquadUp_api\venv\Lib\site-packages\dj_rest_auth\registration\views.py", line 64, in create
    user = self.perform_create(serializer)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Warwick\Documents\Git\SquadUp\SquadUp_api\venv\Lib\site-packages\dj_rest_auth\registration\views.py", lin  File "C:\Python311\Lib\smtplib.py", line 255, in __init__
    (code, msg) = self.connect(host, port)
                  ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\smtplib.py", line 341, in connect
    self.sock = self._get_socket(host, port, self.timeout)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\smtplib.py", line 312, in _get_socket
    return socket.create_connection((host, port), timeout,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\socket.py", line 851, in create_connection
    raise exceptions[0]
  File "C:\Python311\Lib\socket.py", line 836, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [WinError 10061] No connection could be made because the target machine actively refused it       
[22/May/2023 16:15:15] "POST /dj-rest-auth/registration/ HTTP/1.1" 500 209486`

**Comment by BobWritesCode** [comment]
Even though it seems nothing happens and get error, the record is created.
![image](https://github.com/BobWritesCode/squadup_frontend/assets/104802720/50c6a3ea-bacd-4dbe-92bf-b3f641e4ca4a)
![image](https://github.com/BobWritesCode/squadup_frontend/assets/104802720/8ca1ede9-cb2d-467f-837a-a7bd7e6c3c24)

**Comment by BobWritesCode** [comment]
Problem is that the server is trying to connect to SMTP for email verification.  This is not set up in this project so I have turned that off in the backend by putting `ACCOUNT_EMAIL_VERIFICATION = "none"` in the `settings.py`

**Comment by BobWritesCode** [comment]
Create backend issue

**Comment by BobWritesCode** [comment]
Fixed: https://github.com/BobWritesCode/SquadUp_api/issues/38
